create table if not exists public.task_audit_events (
  id bigint generated by default as identity primary key,
  task_id uuid not null references public.tasks(id) on delete cascade,
  action text not null,
  change_summary text not null,
  changed_columns text[] not null default '{}'::text[],
  changed_by_user_id uuid references public.users(id) on delete set null,
  changed_at timestamptz not null default now(),
  details jsonb not null default '{}'::jsonb,
  constraint task_audit_events_action_not_blank check (length(trim(action)) > 0),
  constraint task_audit_events_change_summary_not_blank check (length(trim(change_summary)) > 0)
);

create index if not exists task_audit_events_task_changed_idx
  on public.task_audit_events(task_id, changed_at desc);

create index if not exists task_audit_events_actor_changed_idx
  on public.task_audit_events(changed_by_user_id, changed_at desc);

create or replace function public.task_log_audit_event(
  p_task_id uuid,
  p_action text,
  p_change_summary text,
  p_changed_columns text[] default '{}'::text[],
  p_details jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  actor_id uuid := coalesce(public.current_app_user_id(), auth.uid());
begin
  if p_task_id is null then
    return;
  end if;

  if length(trim(coalesce(p_action, ''))) = 0 then
    raise exception 'Action is required';
  end if;

  if length(trim(coalesce(p_change_summary, ''))) = 0 then
    raise exception 'Change summary is required';
  end if;

  insert into public.task_audit_events (
    task_id,
    action,
    change_summary,
    changed_columns,
    changed_by_user_id,
    details
  )
  values (
    p_task_id,
    trim(p_action),
    trim(p_change_summary),
    coalesce(p_changed_columns, '{}'::text[]),
    actor_id,
    coalesce(p_details, '{}'::jsonb)
  );
end;
$$;

create or replace function public.task_capture_audit_event()
returns trigger
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  old_row jsonb;
  new_row jsonb;
  changed_columns text[] := '{}'::text[];
  changed_labels text[] := '{}'::text[];
  change_count integer := 0;
  summary text;
  details jsonb := '{}'::jsonb;
begin
  if tg_op = 'INSERT' then
    perform public.task_log_audit_event(
      new.id,
      'task.created',
      'Task created',
      array['created'],
      jsonb_build_object(
        'status', new.status,
        'priority', new.priority
      )
    );
    return new;
  end if;

  if tg_op <> 'UPDATE' then
    return coalesce(new, old);
  end if;

  old_row := to_jsonb(old);
  new_row := to_jsonb(new);

  select coalesce(array_agg(diff.key order by diff.key), '{}'::text[])
  into changed_columns
  from (
    select n.key
    from jsonb_each(new_row) as n(key, value)
    where (old_row -> n.key) is distinct from n.value
      and n.key <> all(array['updated_at', 'created_at', 'content_text'])
  ) as diff;

  change_count := coalesce(array_length(changed_columns, 1), 0);
  if change_count = 0 then
    return new;
  end if;

  select coalesce(
    jsonb_object_agg(col, jsonb_build_object('from', old_row -> col, 'to', new_row -> col)),
    '{}'::jsonb
  )
  into details
  from unnest(changed_columns) as col
  where col <> 'content';

  select coalesce(array_agg(mapped.label order by mapped.first_position), '{}'::text[])
  into changed_labels
  from (
    select
      min(entry.position) as first_position,
      case entry.column_name
        when 'title' then 'Title'
        when 'description' then 'Description'
        when 'status' then 'Status'
        when 'priority' then 'Priority'
        when 'start_date' then 'Start date'
        when 'due_date' then 'Due date'
        when 'due_time' then 'Due time'
        when 'assignee_user_id' then 'Primary assignee'
        when 'project_id' then 'Project'
        when 'client_id' then 'Client'
        when 'parent_task_id' then 'Parent task'
        when 'content' then 'Notes'
        when 'last_edited_at' then 'Notes'
        when 'last_edited_by_user_id' then 'Notes'
        else initcap(replace(entry.column_name, '_', ' '))
      end as label
    from unnest(changed_columns) with ordinality as entry(column_name, position)
    group by 2
  ) as mapped;

  change_count := coalesce(array_length(changed_labels, 1), 0);
  if change_count = 1 then
    summary := changed_labels[1] || ' changed';
  else
    summary := 'Changed ' || array_to_string(changed_labels[1:least(4, change_count)], ', ');
    if change_count > 4 then
      summary := summary || format(' and %s more', change_count - 4);
    end if;
  end if;

  perform public.task_log_audit_event(
    new.id,
    'task.updated',
    summary,
    changed_columns,
    details
  );

  return new;
end;
$$;

drop trigger if exists task_capture_audit_event_trigger on public.tasks;
create trigger task_capture_audit_event_trigger
after insert or update on public.tasks
for each row
execute function public.task_capture_audit_event();

alter table public.task_audit_events enable row level security;

drop policy if exists task_audit_events_select on public.task_audit_events;
create policy task_audit_events_select
  on public.task_audit_events
  for select
  to authenticated
  using (public.can_access_task(task_id));

drop policy if exists task_audit_events_insert_block on public.task_audit_events;
create policy task_audit_events_insert_block
  on public.task_audit_events
  for insert
  to authenticated
  with check (false);

drop policy if exists task_audit_events_update_block on public.task_audit_events;
create policy task_audit_events_update_block
  on public.task_audit_events
  for update
  to authenticated
  using (false)
  with check (false);

drop policy if exists task_audit_events_delete_block on public.task_audit_events;
create policy task_audit_events_delete_block
  on public.task_audit_events
  for delete
  to authenticated
  using (false);

grant select on public.task_audit_events to authenticated;
grant execute on function public.task_capture_audit_event() to anon, authenticated;
grant execute on function public.task_log_audit_event(uuid, text, text, text[], jsonb) to anon, authenticated;